// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_GASModel();
RcppExport SEXP _rcpp_module_boot_GGS();
RcppExport SEXP _rcpp_module_boot_HMC();
RcppExport SEXP _rcpp_module_boot_Prior();
RcppExport SEXP _rcpp_module_boot_RWMH();
RcppExport SEXP _rcpp_module_boot_VectorizedPosterior();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_GASModel", (DL_FUNC) &_rcpp_module_boot_GASModel, 0},
    {"_rcpp_module_boot_GGS", (DL_FUNC) &_rcpp_module_boot_GGS, 0},
    {"_rcpp_module_boot_HMC", (DL_FUNC) &_rcpp_module_boot_HMC, 0},
    {"_rcpp_module_boot_Prior", (DL_FUNC) &_rcpp_module_boot_Prior, 0},
    {"_rcpp_module_boot_RWMH", (DL_FUNC) &_rcpp_module_boot_RWMH, 0},
    {"_rcpp_module_boot_VectorizedPosterior", (DL_FUNC) &_rcpp_module_boot_VectorizedPosterior, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesianGAS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
